default_users:
  user1:
    email: 'user1@twotter.com'
    password: '123456'
    password_confirmation: '123456'
  user2:
    email: 'user2@twotter.com'
    password: '123456'
    password_confirmation: '123456'
