default_users:
  user1:
    email: 'user1@twotter.com'
    password: '123456'
    password_confirmation: '123456'
  user2:
    email: 'user2@twotter.com'
    password: '123456'
    password_confirmation: '123456'


default_posts:
  post1:
    message: 'Int64. The integer representation\
     is greater than 53 bits and some programming\
      languages may have difficulty/silent defects in interpreting it. Using a signed 64 bit integ'
    username: user1
  post2:
    message: 'Int64. The integer representation\
     is greater than 53 bits and some programming\
      languages may have difficulty/silent defects in interpreting it. Using a signed 64 bit integ'
    username: user2
  post3:
    message: 'Int64. The integer representation\
     is greater than 53 bits and some programming\
      languages may have difficulty/silent defects in interpreting it. Using a signed 64 bit integer'
    username: user1